### ISSUE TITLE
Bug django_filter version, cannot import name 'FieldDoesNotExist'`

### ISSUE THREAD

**Issue by Alissonrgs** [Alissonrgs/django-react-boilerplate#23]
```python
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/args/.virtualenvs/drb/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django_filters/__init__.py", line 4, in <module>
    from .filters import *
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django_filters/filters.py", line 12, in <module>
    from .conf import settings
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django_filters/conf.py", line 5, in <module>
    from .utils import deprecate
  File "/home/args/.virtualenvs/drb/lib/python3.6/site-packages/django_filters/utils.py", line 10, in <module>
    from django.db.models.fields import FieldDoesNotExist
ImportError: cannot import name 'FieldDoesNotExist'
```

**Comment by Alissonrgs** [comment]
https://github.com/Alissonrgs/django-react-boilerplate/pull/25
